# Generated by Django 4.0.4 on 2022-07-25 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_group_comment_bid_auction_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='cr_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cr_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
