# Generated by Django 4.0.4 on 2022-07-25 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auction_price_money_auction_price_money_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='price',
        ),
    ]
