# Generated by Django 4.0.4 on 2022-07-25 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_auction_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='Price_money',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='Price_money_currency',
            new_name='price_currency',
        ),
    ]
